build:
  tags:
    - public-docker
  image: $CI_REGISTRY/conrads2/ci-images/debian/openmpi
  stage: build
  script:
    - mkdir build
    - cmake -DBUILD_SHARED_LIBS=ON -B build .
    - num_cpus="$(getconf _NPROCESSORS_ONLN)"
    - echo "Building on $num_cpus CPU cores"
    - cmake --build build/ --parallel "$num_cpus"
  artifacts:
    paths:
      - build/

test:
  tags:
    - public-docker
  stage: test
  script:
    - cd build
    - ctest
