.setup:
  parallel:
    matrix:
      - MPI: [mpich, openmpi]
  tags:
    - public-docker
  image: $CI_REGISTRY/conrads2/ci-images/debian/$MPI
  variables:
    BUILD_DIR: build-$MPI
    CFLAGS: -Wextra -Wall -pedantic
    CXXFLAGS: -Wextra -Wall -pedantic
    LDFLAGS: -Wl,-z,defs


build:
  extends: .setup
  stage: build
  script:
    - mkdir "$BUILD_DIR"
    - cmake -DBUILD_SHARED_LIBS=ON -B "$BUILD_DIR" .
    - num_cpus="$(getconf _NPROCESSORS_ONLN)"
    - echo "Building on $num_cpus CPU cores"
    - cmake --build "$BUILD_DIR" --parallel "$num_cpus"
  artifacts:
    paths:
      - $BUILD_DIR


test:
  extends: .setup
  stage: test
  script:
    - cd "$BUILD_DIR"
    - ctest --output-on-failure
