build:
  tags:
    - public-docker
  stage: build
  script:
    - mkdir build
    - cmake -DBUILD_SHARED_LIBS=ON -B build .
    - make -C build
  artifacts:
    paths:
      - build/

test:
  tags:
    - public-docker
  stage: test
  script:
    - cd build
    - ctest
